// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetUmbracoBackOfficeOrganiserApiV1InfoResponse, PostUmbracoBackOfficeOrganiserApiV1OrganiseData, PostUmbracoBackOfficeOrganiserApiV1OrganiseResponse } from './types.gen';

/**
 * @returns unknown OK
 * @throws ApiError
 */
export const getUmbracoBackOfficeOrganiserApiV1Info = (): CancelablePromise<GetUmbracoBackOfficeOrganiserApiV1InfoResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/umbraco/BackOfficeOrganiser/api/v1/info'
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const postUmbracoBackOfficeOrganiserApiV1Organise = (data: PostUmbracoBackOfficeOrganiserApiV1OrganiseData = {}): CancelablePromise<PostUmbracoBackOfficeOrganiserApiV1OrganiseResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/umbraco/BackOfficeOrganiser/api/v1/organise',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            400: 'Bad Request'
        }
    });
};